name: aws-rag-bot
channels:
  - conda-forge
dependencies:
  - tqdm
  - python=3.11
  - fastapi
  - ruff
  - langchain
  - langchain-community
  - aioboto3
  - langchain-aws
  - google-genai
  - google-adk
  - httpx
  - pytest
  - fastmcp
  - pip
  - pip:
      - litellm
      - google-adk
      - google-adk[eval]
      - google-genai
prefix: ./.conda
